'use client';
import { useState } from 'react';
import CoachHub from './coach-dashboard.jsx';
import Image from 'next/image';
import { Activity, ArrowLeft, ArrowRight, Check, CircleAlert, Copy, History, LayoutDashboard, RefreshCw, Search, ShieldCheck, Users, Wallet, X } from 'lucide-react';
import { useAdminResource } from './use-admin-resource.mjs';
import { AuditList, date, LaunchPanel, MARKET_NAMES, MemberDialog, MemberIdentity, Pager, ResourceNotice, ReviewDialog, SIGNAL_NAMES, SignalsPanel, Status, SystemPanel } from './admin-operations-ui.jsx';
const NAV=[['overview','ภาพรวม',LayoutDashboard],['members','สมาชิก',Users],['renewals','ต่ออายุ',Wallet],['signals','สัญญาณและผลลัพธ์',Activity],['coaches','พอร์ตโค้ช',Users],['audit','ประวัติรายการ',History],['system','สถานะระบบ',ShieldCheck]];
const ERRORS={FORBIDDEN:'บัญชีนี้ไม่มีสิทธิผู้ดูแล',PORTFOLIO_MISMATCH:'เลขพอร์ตไม่ตรงกับที่สมาชิกแจ้ง',INVALID_PORTFOLIO:'กรุณาตรวจรูปแบบเลขพอร์ต',PORTFOLIO_NOT_VERIFIED:'ต้องตรวจบัญชีหุ้นให้ผ่านก่อน',REQUEST_UNAVAILABLE:'รายการถูกจัดการไปแล้ว กรุณารีเฟรช',INVALID_CREDIT_AMOUNT:'เครดิตต้องเป็นจำนวนเต็ม 1–1,000',INVALID_REQUEST_ID:'รหัสรายการไม่ตรงกับรายการเดิม กรุณาเปิดรายการใหม่',INVALID_NOTE:'หมายเหตุยาวเกินกำหนด',CODE_UNAVAILABLE:'โค้ดถูกใช้ ยกเลิก หรือหมดอายุแล้ว',PAYMENT_CONFIRMATION_REQUIRED:'กรุณายืนยันการรับชำระก่อน',RATE_LIMITED:'ทำรายการถี่เกินไป กรุณารอสักครู่'};
function SectionTitle({title,detail,onRefresh,loading}){return <div className="admin-section-title"><div><h2>{title}</h2><p>{detail}</p></div><button className="account-secondary" onClick={onRefresh} disabled={loading}><RefreshCw size={16}/>{loading?'กำลังโหลด':'รีเฟรช'}</button></div>;}
export default function AdminConsole(){
  const [tab,setTab]=useState('overview'),[query,setQuery]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(1);
  const [renewalState,setRenewalState]=useState('pending'),[renewalPage,setRenewalPage]=useState(1),[auditPage,setAuditPage]=useState(1);
  const [signalMarket,setSignalMarket]=useState('all'),[signalStatus,setSignalStatus]=useState('all'),[signalPage,setSignalPage]=useState(1);
  const [selected,setSelected]=useState(null),[detailVersion,setDetailVersion]=useState(0),[draft,setDraft]=useState(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[issued,setIssued]=useState(null),[copied,setCopied]=useState(false);
  const memberParams=new URLSearchParams({q:search,filter,page:String(page),renewalState,renewalPage:String(renewalPage)});
  const members=useAdminResource(`/api/admin/memberships?${memberParams}`);
  const system=useAdminResource('/api/admin/system',tab==='overview'||tab==='system');
  const audit=useAdminResource(`/api/admin/audit?page=${auditPage}`,tab==='audit');
  const signals=useAdminResource(`/api/admin/signals?${new URLSearchParams({market:signalMarket,status:signalStatus,page:String(signalPage)})}`,tab==='signals');
  const data=members.data,summary=data?.summary;
  function review(value){setError('');setMessage('');setDraft({...value,body:{...value.body,operationId:crypto.randomUUID()}});}
  async function act(body){
    if(busy)return;setBusy(true);setError('');setMessage('');
    try{
      const response=await fetch('/api/admin/memberships',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});
      const payload=await response.json();
      if(!response.ok){setError(ERRORS[payload.error]||'ทำรายการไม่สำเร็จ กรุณารีเฟรชข้อมูล');return;}
      setMessage(`${draft.title}สำเร็จ · ${draft.memberName}`);
      if(payload.code){setIssued({code:payload.code,id:payload.codeId,name:draft.memberName});setCopied(false);setSelected(null);}
      setDraft(null);setDetailVersion(value=>value+1);members.reload();audit.reload();
    }catch{setError(['issue-code','grant-ai-credits'].includes(body.action)?'ยังไม่ได้รับคำตอบจากเซิร์ฟเวอร์ กดยืนยันรายการเดิมอีกครั้งได้ ระบบจะไม่ทำซ้ำ':'ยังไม่ได้รับคำตอบจากเซิร์ฟเวอร์ กรุณาปิดหน้าต่างและรีเฟรชตรวจสถานะก่อนทำรายการอีกครั้ง');}
    finally{setBusy(false);}
  }
  function openPending(){setTab('members');setFilter('pending');setSearch('');setQuery('');setPage(1);}
  function refresh(){members.reload();if(tab==='overview'||tab==='system')system.reload();if(tab==='audit')audit.reload();if(tab==='signals')signals.reload();}
  async function copyCode(){try{await navigator.clipboard.writeText(issued.code);setCopied(true);}catch{setError('คัดลอกไม่ได้ กรุณาเลือกโค้ดแล้วคัดลอกด้วยตนเอง');}}
  return <div className="account-page admin-page admin-operations">
    <header className="account-topbar"><a className="account-brand" href="/"><span><Image src="/nugaom-mascot.png" width={38} height={38} alt=""/></span><span><strong>Nugaom AI Pick</strong><small>ศูนย์ดูแลลูกค้า</small></span></a><a className="account-back" href="/account"><ArrowLeft size={16}/>บัญชีของฉัน</a></header>
    <div className="account-hero"><div className="account-hero-inner"><span className="account-kicker">สำหรับผู้ดูแล</span><h1>จัดการลูกค้า <em>และดูแลสัญญาณ</em></h1><p>ข้อมูลสมาชิกจาก LINE รายการต่ออายุ และเหตุการณ์สแกนจากระบบเดียวกัน</p></div></div>
    <div className="account-layout"><aside className="account-nav"><span className="account-nav-label">ศูนย์ควบคุม</span>{NAV.map(([id,label,Icon])=><button key={id} className={tab===id?'selected':''} onClick={()=>{setTab(id);setError('');}}><Icon size={18}/>{label}{id==='members'&&summary?.pendingPortfolios>0&&<i>{summary.pendingPortfolios}</i>}{id==='renewals'&&summary?.pendingRenewals>0&&<i>{summary.pendingRenewals}</i>}</button>)}<a className="admin-nav-link" href="/"><ArrowLeft size={17}/>กลับหน้าตลาด</a></aside>
      <main className="account-main">
        {!draft&&error&&<div className="account-alert error" role="alert"><CircleAlert size={17}/>{error}</div>}{message&&<div className="account-alert success" role="status"><Check size={17}/>{message}</div>}
        {issued&&<div className="account-issued" role="status"><div className="admin-issued-head"><strong>โค้ดรายเดือนของ {issued.name}</strong><button className="account-secondary" onClick={()=>setIssued(null)} aria-label="ซ่อนโค้ด"><X size={16}/></button></div><code>{issued.code}</code><span>อ้างอิง {issued.id?.slice(0,8)} · ใช้ได้หนึ่งครั้งภายใน 30 วัน ระบบเก็บเฉพาะแฮชของโค้ด ส่งให้สมาชิกผ่านช่องทางที่คุณดูแล</span><button className="account-secondary" onClick={copyCode}><Copy size={15}/>{copied?'คัดลอกแล้ว':'คัดลอกโค้ด'}</button></div>}
        {tab==='overview'&&<>
          <section className="account-card"><SectionTitle title="ภาพรวมงานวันนี้" detail={`ข้อมูลสมาชิกอัปเดต ${date(data?.updatedAt)}`} onRefresh={refresh} loading={members.loading||system.loading}/><ResourceNotice resource={members}/>{summary&&<><div className="admin-stat-grid"><article><span>ลูกค้า LINE ทั้งหมด</span><strong>{summary.total}</strong><small>รวมคนที่ยังไม่แจ้งพอร์ต</small></article><article><span>กำลังทดลองใช้ฟรี</span><strong>{summary.trials}</strong><small>สิทธิทดลอง 14 วัน</small></article><article><span>สมาชิกที่มีสิทธิ</span><strong>{summary.subscribers}</strong><small>ต่ออายุแล้ว</small></article><article><span>สิทธิหมดอายุ</span><strong>{summary.expired}</strong><small>รอต่ออายุ</small></article></div><div className="admin-queue-grid"><button onClick={openPending}><span><ShieldCheck size={20}/>บัญชีหุ้นรอตรวจ</span><strong>{summary.pendingPortfolios}</strong><ArrowRight size={18}/></button><button onClick={()=>{setTab('renewals');setRenewalState('pending');setRenewalPage(1);}}><span><Wallet size={20}/>คำขอต่ออายุ</span><strong>{summary.pendingRenewals}</strong><ArrowRight size={18}/></button></div><p className="admin-explainer">ลูกค้าที่ยังไม่แจ้งพอร์ต / ต้องแจ้งใหม่ {summary.onboarding} คน ตรวจบัญชีหุ้นจากหลักฐานก่อนออกโค้ดหรืออนุมัติสมาชิก</p></>}</section>
          <ResourceNotice resource={system}/>{system.data&&<><LaunchPanel launch={system.data.launch}/><section className="account-card"><SectionTitle title="สัญญาณที่กำลังติดตาม" detail="แสดงสถานะจากบันทึกระบบ" onRefresh={system.reload} loading={system.loading}/><div className="admin-stat-grid compact"><article><span>รอเข้าเงื่อนไข</span><strong>{system.data.outcomes.WAITING_FOR_ENTRY||0}</strong></article><article><span>เข้าแล้ว ยังติดตาม</span><strong>{system.data.outcomes.OPEN||0}</strong></article><article><span>ถึงเป้าหมาย</span><strong>{system.data.outcomes.TARGET||0}</strong></article><article><span>รอตรวจข้อมูล</span><strong>{(system.data.outcomes.REVIEW||0)+(system.data.outcomes.AMBIGUOUS||0)}</strong></article></div><button className="account-secondary" onClick={()=>setTab('signals')}>ดูราคาเข้า–ออกและผลลัพธ์<ArrowRight size={16}/></button></section></>}
        </>}
        {tab==='members'&&<section className="account-card"><SectionTitle title="สมาชิกทั้งหมด" detail="ค้นหาลูกค้า LINE และจัดการสิทธิจากรายละเอียดสมาชิก" onRefresh={members.reload} loading={members.loading}/><div className="admin-toolbar"><form className="admin-search" onSubmit={event=>{event.preventDefault();setSearch(query.trim());setPage(1);}}><Search size={17}/><input aria-label="ค้นหาสมาชิก" value={query} maxLength={80} onChange={event=>setQuery(event.target.value)} placeholder="ชื่อ โบรกเกอร์ หรือเลขพอร์ต 4 หลักท้าย"/><button className="account-secondary">ค้นหา</button></form><label>สถานะ<select value={filter} onChange={event=>{setFilter(event.target.value);setPage(1);}}><option value="all">ทั้งหมด</option><option value="pending">รอตรวจพอร์ต</option><option value="trial">กำลังทดลอง</option><option value="subscriber">สมาชิก</option><option value="expired">หมดอายุ</option><option value="onboarding">ยังไม่แจ้งพอร์ต</option><option value="portfolio-fix">ต้องแจ้งใหม่</option></select></label></div><ResourceNotice resource={members}/>{data&&<><div className="admin-member-list">{data.members.map(member=><article key={member.id}><MemberIdentity member={member}/><div className="admin-member-meta"><Status value={member.tier}>{member.tierLabel}</Status><small>{member.portfolio_status==='pending'?'รอตรวจพอร์ต':member.portfolio_status==='verified'?'บัญชีหุ้นยืนยันแล้ว':'ยังไม่ยืนยันบัญชีหุ้น'}</small><small>เครดิต AI {member.ai_credits}</small></div><button className="account-secondary" onClick={()=>setSelected(member.id)} disabled={members.loading}>ดูและจัดการ<ArrowRight size={15}/></button></article>)}</div>{!data.members.length&&<p className="account-empty">ไม่พบสมาชิกในตัวกรองนี้</p>}<Pager data={data} onPage={setPage} loading={members.loading}/></>}</section>}
        {tab==='renewals'&&<section className="account-card"><SectionTitle title="คำขอต่ออายุ" detail="อนุมัติหลังตรวจยอดรับชำระจริง สิทธิเดิมที่เหลืออยู่จะต่อเนื่อง" onRefresh={members.reload} loading={members.loading}/><div className="admin-toolbar"><label>รายการ<select value={renewalState} onChange={event=>{setRenewalState(event.target.value);setRenewalPage(1);}}><option value="pending">รอตรวจ</option><option value="approved">อนุมัติแล้ว</option><option value="rejected">ปฏิเสธแล้ว</option><option value="all">ทั้งหมด</option></select></label></div><ResourceNotice resource={members}/>{data&&<><div className="admin-renewal-list">{data.renewals.map(item=><article key={item.id}><div><strong>{item.display_name}</strong><p>{item.broker} · ••{item.portfolio_last4}</p><small>ขอเมื่อ {date(item.created_at)}</small>{item.resolved_at&&<small>จัดการ {date(item.resolved_at)} · {item.resolved_by_name}</small>}</div><div className="admin-row-actions"><Status value={item.status}>{({pending:'รอตรวจ',approved:'อนุมัติแล้ว',rejected:'ปฏิเสธแล้ว'})[item.status]}</Status><button className="account-secondary" onClick={()=>setSelected(item.member_id)}>รายละเอียดสมาชิก</button>{item.status==='pending'&&<><button className="account-primary" disabled={members.loading} onClick={()=>review({body:{action:'approve-renewal',requestId:item.id},title:'อนุมัติต่ออายุ',detail:'เปิดสิทธิอีกหนึ่งเดือนหลังตรวจยอดชำระแล้ว',memberName:item.display_name})}>ตรวจยอดและเปิดสิทธิ</button><button className="account-secondary" disabled={members.loading} onClick={()=>review({body:{action:'reject-renewal',requestId:item.id},title:'ปฏิเสธคำขอต่ออายุ',detail:'สิทธิเดิมยังคงอยู่ ลูกค้าสามารถส่งคำขอใหม่ได้',memberName:item.display_name})}>ปฏิเสธคำขอ</button></>}</div></article>)}</div>{!data.renewals.length&&<p className="account-empty">ไม่มีคำขอในตัวกรองนี้</p>}<Pager data={{total:data.renewalTotal,page:data.renewalPage,pageSize:data.renewalPageSize}} onPage={setRenewalPage} loading={members.loading}/></>}</section>}
        {tab==='signals'&&<section className="account-card"><SectionTitle title="สัญญาณและผลลัพธ์" detail="ตรวจราคาเข้าจริงในบันทึก ราคาออก และลำดับแจ้งเตือน" onRefresh={signals.reload} loading={signals.loading}/><div className="admin-toolbar"><label>ตลาด<select value={signalMarket} onChange={event=>{setSignalMarket(event.target.value);setSignalPage(1);}}><option value="all">ทุกตลาด</option>{Object.entries(MARKET_NAMES).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label>สถานะ<select value={signalStatus} onChange={event=>{setSignalStatus(event.target.value);setSignalPage(1);}}><option value="all">ทุกสถานะ</option>{Object.entries(SIGNAL_NAMES).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label></div><ResourceNotice resource={signals}/>{signals.data&&<SignalsPanel data={signals.data} onPage={setSignalPage} loading={signals.loading}/>}</section>}
        {tab==='coaches'&&<section className="account-card"><CoachHub mode="admin"/></section>}
        {tab==='audit'&&<section className="account-card"><SectionTitle title="ประวัติรายการ" detail="ดูว่าใครจัดการสิทธิและเครดิตให้ลูกค้าคนไหน เมื่อไร" onRefresh={audit.reload} loading={audit.loading}/><ResourceNotice resource={audit}/>{audit.data&&<><AuditList events={audit.data.events}/><Pager data={audit.data} onPage={setAuditPage} loading={audit.loading}/></>}</section>}
        {tab==='system'&&<section className="account-card"><SectionTitle title="สถานะระบบและจุดที่ต้องแก้" detail={`อัปเดต ${date(system.data?.updatedAt)}`} onRefresh={system.reload} loading={system.loading}/><ResourceNotice resource={system}/>{system.data&&<SystemPanel system={system.data}/>}</section>}
      </main>
    </div><footer className="account-footer"><span>© 2026 Nugaom AI Pick</span><span>ข้อมูลนี้เปิดให้เฉพาะผู้ดูแลที่กำหนดในระบบ</span></footer>
    {selected&&<MemberDialog key={selected} id={selected} version={detailVersion} message={message} onClose={()=>setSelected(null)} onReview={review}/>}
    {draft&&<ReviewDialog key={draft.body.operationId} draft={draft} busy={busy} error={error} onClose={()=>{setDraft(null);setError('');}} onConfirm={act}/>}
  </div>;
}
