'use client';
import { useEffect, useRef, useState } from 'react';
import { Activity, Check, ChevronLeft, ChevronRight, CircleAlert, KeyRound, ShieldCheck, X } from 'lucide-react';
import MemberAvatar from './member-avatar.jsx';
import WebullSdkStatus from './webull-sdk-status.jsx';
import { useAdminResource } from './use-admin-resource.mjs';
export const MARKET_NAMES={thai:'หุ้นไทย',dr:'DR',us:'หุ้นสหรัฐฯ',tfex:'TFEX',forex:'Forex'};
export const SIGNAL_NAMES={WAITING_FOR_ENTRY:'รอเข้าเงื่อนไข',OPEN:'เข้าแล้ว',TARGET:'ถึงเป้าหมาย',STOP:'ตัดขาดทุน',EXIT:'ปิดตามแผน',EXPIRED:'หมดเวลารอเข้า',REVIEW:'รอตรวจข้อมูล',AMBIGUOUS:'แท่งแตะทั้งเป้าและจุดตัดขาดทุน'};
const WORKER_NAMES={healthy:'ทำงานปกติ',running:'กำลังทำงาน','outside-session':'นอกเวลาสแกน',complete:'ตรวจครบ','candidate-degraded':'ข้อมูลบางตัวขัดข้อง',degraded:'ข้อมูลขัดข้อง',stale:'รอบสแกนล่าช้า',offline:'ไม่ติดต่อ','not-running':'ยังไม่ทำงาน','awaiting-first-run':'รอรอบแรก'};
const AUDIT_NAMES={portfolio_submitted:'แจ้งบัญชีหุ้น',portfolio_verified:'ยืนยันบัญชีหุ้น',portfolio_rejected:'ปฏิเสธบัญชีหุ้น',code_issued:'ออกโค้ดรายเดือน',code_redeemed:'ใช้โค้ดต่ออายุ',code_revoked:'ยกเลิกโค้ด',renewal_requested:'ขอต่ออายุ',renewal_approved:'อนุมัติต่ออายุ',renewal_rejected:'ปฏิเสธต่ออายุ','admin-grant':'เพิ่มเครดิต AI','ai-question':'ใช้เครดิตถาม AI','interrupted-question-refund':'คืนเครดิตเมื่อคำถามขัดข้อง'};
export function date(value){return value&&Number.isFinite(new Date(value).valueOf())?new Date(value).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}):'—';}
export function price(value){return Number.isFinite(value)?value.toLocaleString('en-US',{maximumFractionDigits:6}):'—';}
export function Status({value,children}){return <span className={`admin-pill ${['ready','healthy','running','subscriber','verified','TARGET','approved'].includes(value)?'positive':['blocked','expired','STOP','REVIEW','AMBIGUOUS','rejected'].includes(value)?'negative':'neutral'}`}>{children||value}</span>;}
export function MemberIdentity({member}){return <div className="admin-member-identity"><span className="admin-avatar"><MemberAvatar account={{pictureUrl:member.picture_url,displayName:member.display_name}} size={42}/></span><div><strong>{member.display_name}</strong><small>{member.portfolio_last4?`${member.broker} · ••${member.portfolio_last4}`:'ยังไม่แจ้งบัญชีหุ้น'}</small></div></div>;}
export function Pager({data,onPage,loading}){if(!data)return null;const pages=Math.max(1,Math.ceil(data.total/data.pageSize));return <nav className="admin-pager" aria-label="แบ่งหน้ารายการ"><span>{data.total.toLocaleString()} รายการ · หน้า {data.page}/{pages}</span><div><button className="account-secondary" disabled={loading||data.page<=1} onClick={()=>onPage(data.page-1)} aria-label="หน้าก่อน"><ChevronLeft size={16}/></button><button className="account-secondary" disabled={loading||data.page>=pages} onClick={()=>onPage(data.page+1)} aria-label="หน้าถัดไป"><ChevronRight size={16}/></button></div></nav>;}
export function ResourceNotice({resource}){return resource.loading&&!resource.data?<div className="account-card account-skeleton"><span/><span/><span/></div>:resource.error?<div className="account-alert error" role="alert"><CircleAlert size={17}/>{resource.error==='FORBIDDEN'?'สิทธิผู้ดูแลไม่พร้อม กรุณาเข้าสู่ระบบ LINE อีกครั้ง':'อ่านข้อมูลไม่ได้ กรุณาลองใหม่'}<button className="account-secondary" onClick={resource.reload}>ลองใหม่</button></div>:null;}
function Modal({title,onClose,children,compact=false}){const dialog=useRef(null);useEffect(()=>{const element=dialog.current;if(!element.open)element.showModal();return ()=>{if(element.open)element.close();};},[]);return <dialog className={`admin-dialog account-page ${compact?'compact':''}`} ref={dialog} aria-label={title} onCancel={event=>{event.preventDefault();onClose();}}><div className="admin-dialog-head"><h2>{title}</h2><button className="account-secondary" onClick={onClose} aria-label="ปิดหน้าต่าง"><X size={18}/></button></div>{children}</dialog>;}
function eventDetail(event){if(!event.details)return '';try{const data=JSON.parse(event.details);if(data.subscriptionEndsAt)return `สิทธิถึง ${date(data.subscriptionEndsAt)}${data.reference?` · อ้างอิง ${data.reference}`:''}`;}catch{/* Older audit entries are text. */}return event.details.length>200?`${event.details.slice(0,200)}…`:event.details;}
export function AuditList({events=[]}){return events.length?<div className="admin-audit-list">{events.map(event=><article key={`${event.event_type}:${event.id}`}><span className="admin-audit-dot"/><div><strong>{AUDIT_NAMES[event.event_type]||'รายการบัญชี'}</strong><p>{event.member_name} · {event.actor_name?`โดย ${event.actor_name}`:'ระบบอัตโนมัติ'}</p>{event.amount!==null&&<small>{event.amount>0?'+':''}{event.amount} เครดิต · หลังรายการ {event.balance_after}</small>}{(event.note||event.details)&&<small>{event.note||eventDetail(event)}</small>}<time>{date(event.created_at)}</time></div></article>)}</div>:<p className="account-empty">ยังไม่มีประวัติรายการ</p>;}
export function MemberDialog({id,onClose,onReview,version,message}){
  const resource=useAdminResource(`/api/admin/members/${encodeURIComponent(id)}?v=${version}`);
  const [number,setNumber]=useState(''),[amount,setAmount]=useState('10'),[note,setNote]=useState('');
  useEffect(()=>{setNumber('');setNote('');},[version]);
  const data=resource.data,member=data?.member;
  const review=(body,title,detail)=>onReview({body:{...body,memberId:id},title,detail,memberName:member.display_name});
  return <Modal title="รายละเอียดสมาชิก" onClose={onClose}>{message&&<div className="account-alert success" role="status"><Check size={17}/>{message}</div>}<ResourceNotice resource={resource}/>{member&&<>
    <div className="admin-detail-intro"><MemberIdentity member={member}/><Status value={member.tier}>{member.tierLabel}</Status></div>
    <div className="admin-detail-grid"><div><span>เริ่มทดลอง</span><strong>{date(member.trial_started_at)}</strong></div><div><span>ทดลองถึง</span><strong>{date(member.trial_ends_at)}</strong></div><div><span>สมาชิกถึง</span><strong>{date(member.subscription_ends_at)}</strong></div><div><span>อัปเดตบัญชีล่าสุด</span><strong>{date(member.updated_at)}</strong></div></div>
    <section className="admin-detail-section"><h3>บัญชีหุ้น</h3><p>{member.portfolio_status==='verified'?'ตรวจสอบแล้ว':member.portfolio_status==='pending'?'รอตรวจสอบ':'ยังไม่ได้แจ้งบัญชีหุ้น'}</p>{member.portfolio_status==='pending'&&<><form className="admin-inline-form" onSubmit={event=>{event.preventDefault();review({action:'verify',number},'ยืนยันบัญชีหุ้น','เลขเต็มต้องตรงกับหลักฐานที่ตรวจสอบ');}}><label>เลขพอร์ตเต็มจากหลักฐาน<input value={number} onChange={event=>setNumber(event.target.value)} autoComplete="off" required minLength={5} maxLength={30} placeholder="ใช้เทียบกับเลขที่ลูกค้าแจ้ง"/></label><button className="account-primary" disabled={resource.loading}>ตรวจเลขพอร์ต</button></form><button className="account-secondary" disabled={resource.loading} onClick={()=>review({action:'reject-portfolio'},'ปฏิเสธบัญชีหุ้น','ลูกค้าจะแจ้งเลขพอร์ตใหม่ได้ ระยะทดลองเดิมยังนับต่อ')}>เลขพอร์ตไม่ผ่าน</button></>}{member.portfolio_status==='verified'&&<button className="account-primary" disabled={resource.loading} onClick={()=>review({action:'issue-code'},'ออกโค้ดรายเดือน','โค้ดผูกกับสมาชิกคนนี้ ใช้ได้หนึ่งครั้งภายใน 30 วัน')}><KeyRound size={16}/>ออกโค้ดรายเดือน</button>}</section>
    <section className="admin-detail-section"><h3>เครดิตน้องนักออม AI</h3><p>คงเหลือ {data.quota.credits} เครดิต · คำถามฟรีวันนี้เหลือ {data.quota.freeRemaining}/5</p><form className="admin-credit-form" onSubmit={event=>{event.preventDefault();review({action:'grant-ai-credits',amount:Number(amount),note},'เพิ่มเครดิต AI',`เพิ่ม ${amount} เครดิตให้สมาชิกคนนี้`);}}><label>จำนวนเครดิต<input type="number" min="1" max="1000" required value={amount} onChange={event=>setAmount(event.target.value)}/></label><label>หมายเหตุ / อ้างอิงรายการ<input maxLength={200} value={note} onChange={event=>setNote(event.target.value)} placeholder="ระบุเพื่อค้นประวัติภายหลัง"/></label><button className="account-secondary" disabled={resource.loading}>ตรวจรายการเพิ่มเครดิต</button></form></section>
    <section className="admin-detail-section"><h3>โค้ดรายเดือนล่าสุด</h3>{data.codes.length?data.codes.map(code=><div key={code.id} className="admin-code-row"><div><Status value={code.status}>{({available:'ยังใช้ได้',redeemed:'ใช้แล้ว',revoked:'ยกเลิกแล้ว',expired:'หมดอายุ'})[code.status]}</Status><small>อ้างอิง {code.id.slice(0,8)} · ออก {date(code.created_at)} · หมดอายุ {date(code.expires_at)}</small></div>{code.status==='available'&&<button className="account-secondary" disabled={resource.loading} onClick={()=>review({action:'revoke-code',codeId:code.id},'ยกเลิกโค้ดรายเดือน','โค้ดนี้จะใช้ต่ออายุไม่ได้ โดยไม่กระทบสิทธิสมาชิกปัจจุบัน')}>ยกเลิกโค้ด</button>}</div>):<p className="account-empty">ยังไม่เคยออกโค้ด</p>}</section>
    <section className="admin-detail-section"><h3>การใช้งานที่บันทึก</h3><div className="admin-detail-grid"><div><span>หุ้นโปรด</span><strong>{data.workspace.favorites} ตัว</strong></div><div><span>รายการพอร์ต</span><strong>{data.workspace.holdings} ตัว</strong></div><div><span>การเข้าสู่ระบบที่ยังมีอายุ</span><strong>{data.workspace.sessions}</strong></div><div><span>สมัครครั้งแรก</span><strong>{date(member.created_at)}</strong></div></div></section>
    <section className="admin-detail-section"><h3>ประวัติล่าสุด</h3><AuditList events={data.audit.events}/><small>แสดง {data.audit.events.length} จาก {data.audit.total} รายการ</small></section>
  </>}</Modal>;
}
export function ReviewDialog({draft,busy,error,onClose,onConfirm}){const [payment,setPayment]=useState(false),[reference,setReference]=useState('');return <Modal title={draft.title} onClose={()=>{if(!busy)onClose();}} compact><form className="admin-review-form" onSubmit={event=>{event.preventDefault();onConfirm({...draft.body,...(draft.body.action==='approve-renewal'?{paymentConfirmed:payment,reference}:{})});}}><strong>{draft.memberName}</strong><p>{draft.detail}</p>{draft.body.action==='approve-renewal'&&<><label>อ้างอิงยอดรับชำระ<input maxLength={160} value={reference} onChange={event=>setReference(event.target.value)} placeholder="เลขรายการหรือหมายเหตุ"/></label><label className="admin-checkbox"><input type="checkbox" checked={payment} onChange={event=>setPayment(event.target.checked)} required/>ตรวจสอบว่าได้รับชำระแล้ว</label></>}{error&&<div className="account-alert error" role="alert">{error}</div>}<div className="admin-review-actions"><button type="button" className="account-secondary" disabled={busy} onClick={onClose}>กลับไปแก้ไข</button><button className="account-primary" disabled={busy}>{busy?'กำลังบันทึก…':'ยืนยันรายการ'}<Check size={16}/></button></div></form></Modal>;}
export function LaunchPanel({launch}){return <section className="admin-launch"><div><ShieldCheck size={22}/><div><h3>{launch?.ready?'ตั้งค่าระบบสำหรับเปิดลูกค้าครบแล้ว':'ความพร้อมก่อนเปิดรับลูกค้า'}</h3><p>{launch?.ready?'ยังต้องตรวจเส้นทางลูกค้าบนเว็บจริงก่อนประชาสัมพันธ์':'หลังบ้านจัดการข้อมูลได้ แต่เว็บลูกค้ายังต้องขึ้นระบบถาวร'}</p></div></div><div className="admin-launch-checks">{launch?.checks?.map(check=><article key={check.id}><Status value={check.status}>{check.status==='ready'?'พร้อม':check.status==='configured'?'ตั้งค่าแล้ว':'ยังไม่พร้อม'}</Status><div><strong>{check.label}</strong><small>{check.detail}</small></div></article>)}</div></section>;}
export function SystemPanel({system}){return <>
  <LaunchPanel launch={system.launch}/><div className="admin-worker"><Activity size={18}/><span>ตัวทำงานสแกน</span><strong className={system.workerProcess?.status==='running'?'ok':'bad'}>{WORKER_NAMES[system.workerProcess?.status]||'ไม่ทราบสถานะ'}</strong><small>ติดต่อ {date(system.workerProcess?.lastSeenAt)}</small></div>
  <div className="admin-market-grid">{system.markets.map(market=>{const coverage=system.coverage[market.id],worker=system.workers[market.id];return <article className="admin-market-card" key={market.id}><div><strong>{MARKET_NAMES[market.id]}</strong><Status value={market.status==='active'?'ready':'blocked'}>{market.status==='active'?'เปิดสแกน':'ยังไม่เปิดสแกน'}</Status></div><p>{market.reason||market.mode}</p>{worker&&<small>{WORKER_NAMES[worker.status]||'ต้องตรวจสถานะ'} · ล่าสุด {date(worker.lastRunAt)}</small>}{coverage&&<><div className="admin-progress"><span style={{width:`${Math.min(100,(coverage.done+coverage.ineligible+coverage.unavailable)/Math.max(1,coverage.expected)*100)}%`}}/></div><p>ตรวจแล้ว {coverage.done+coverage.ineligible+coverage.unavailable}/{coverage.expected} ตัว</p><small>ไม่เข้าเกณฑ์ {coverage.ineligible} · ข้อมูลใช้ไม่ได้ {coverage.unavailable} · รอลองใหม่ {coverage.retry}</small>{coverage.remaining>0&&<small>ยังค้าง {coverage.remaining} ตัว</small>}{(coverage.unavailableSymbols?.length>0||coverage.retrySymbols?.length>0)&&<details><summary>ดูรายการที่ต้องตรวจ</summary>{[...(coverage.unavailableSymbols||[]),...(coverage.retrySymbols||[])].map(item=><p key={item.symbol}>{item.symbol} · {item.reason||'แหล่งข้อมูลยังไม่พร้อม'}</p>)}</details>}</>}</article>;})}</div>
  <h3>รอบสแกนล่าสุด</h3><div className="admin-runs">{system.runs.map(run=><div key={run.id}><strong>{MARKET_NAMES[run.market]}</strong><span>{run.errorCode?'ข้อมูลบางส่วนขัดข้อง':run.status==='COMPLETE'?'จบรอบ':'กำลังตรวจ'} · ตรวจ {run.scanned} · พบแผน {run.candidates}</span><small>{date(run.finishedAt||run.startedAt)}</small></div>)}</div><details className="admin-detail-section"><summary>การเชื่อมต่อ Webull</summary><WebullSdkStatus data={system.webull}/></details>
</>;}
export function SignalsPanel({data,onPage,loading}){return <><div className="admin-stat-grid compact"><article><span>เข้าแล้วทั้งหมด</span><strong>{data.summary.entered}</strong></article><article><span>ปิดและมีราคาเข้า–ออก</span><strong>{data.summary.closed}/100</strong></article><article><span>ชนะ / แพ้</span><strong>{data.summary.wins} / {data.summary.losses}</strong></article><article><span>อัตราชนะจากไม้ที่ปิด</span><strong>{data.summary.winRate===null?'—':`${data.summary.winRate.toFixed(1)}%`}</strong></article></div><p className="admin-explainer">คำนวณจากสัญญาณที่เข้าและปิดจริงในบันทึกล่าสุดไม่เกิน 100 ไม้ ราคาอ้างอิงจากแท่ง ไม่ใช่ผลซื้อขายในพอร์ตลูกค้า ตัวรอเข้า/หมดเวลารอไม่ถูกนับเป็นแพ้</p><div className="admin-signal-list">{data.signals.map(signal=><article key={signal.id}><header><div><strong>{signal.symbol}</strong><small>{MARKET_NAMES[signal.market]}</small></div><Status value={signal.status}>{SIGNAL_NAMES[signal.status]||signal.status}</Status></header><div className="admin-signal-prices"><div><span>{signal.enteredAt?'ราคาเข้าในบันทึก':'จุดเข้าตามแผน'}</span><strong>{price(signal.entryPrice??signal.plannedEntry)}</strong></div><div><span>ราคาออกในบันทึก</span><strong>{price(signal.exitPrice)}</strong></div><div><span>เป้าหมาย</span><strong>{price(signal.target)}</strong></div><div><span>ตัดขาดทุน</span><strong>{price(signal.stopLoss)}</strong></div></div><details><summary>ลำดับเหตุการณ์ · เผยแพร่ {date(signal.publishedAt)}</summary>{signal.events.map((event,index)=><p key={`${event.type}:${index}`}><strong>{({PICK_READY:'พบแผน',ENTRY:'เข้าเงื่อนไข',TARGET:'ถึงเป้าหมาย',STOP:'ตัดขาดทุน',EXIT:'ปิดตามแผน',EXPIRED:'หมดเวลารอเข้า',DATA_GAP:'ข้อมูลขาดช่วง',AMBIGUOUS:'ไม่ทราบลำดับการแตะราคา'})[event.type]||'เหตุการณ์สัญญาณ'}</strong> · {price(event.price)} · {date(event.createdAt)}<small>{event.detail}</small></p>)}</details></article>)}</div>{!data.signals.length&&<p className="account-empty">ยังไม่มีสัญญาณในตัวกรองนี้</p>}<Pager data={data} onPage={onPage} loading={loading}/></>;}
