'use client';

import { useMemo, useState } from 'react';
import { analyzeIndicatorDetails } from '../analysis/indicator-details.mjs';
import { formatQuotePrice } from '../markets/quote-format.mjs';

function number(value, digits = 2) {
  return typeof value === 'number' && Number.isFinite(value)
    ? value.toLocaleString('en-US', { minimumFractionDigits: digits, maximumFractionDigits: digits }) : '—';
}

function Metric({ label, value, note, tone = '' }) {
  return <div className="toolbox-metric"><span>{label}<small>{note}</small></span><strong className={tone}>{value}</strong></div>;
}

export default function ChartToolbox({ asset, bars, analysis, tradePlan, freshness, latestDay, timeframe = '1D', chartOnly=false, indicators, onToggleIndicator, onOpenAutomation }) {
  const [expanded, setExpanded] = useState(true);
  const [tab, setTab] = useState('indicators');
  const [category, setCategory] = useState('trend');
  const [openGroup, setOpenGroup] = useState('levels');
  const details = useMemo(() => { const base = analyzeIndicatorDetails(bars, timeframe); return base ? { ...base, pivots: analysis?.levels?.pivots ?? null } : null; }, [bars, timeframe, analysis]);
  const hasData = Boolean(analysis && details);
  const current = hasData && freshness === 'recent' && !chartOnly;
  const groups = (category === 'trend'
    ? [['levels', 'Pivot Points & Levels'], ['averages', 'Trend Indicators'], ['volatility', 'Volatility'], ['volume', 'Volume']]
    : [['momentum', 'Momentum Oscillators'], ['macd', 'MACD & Signal']]).filter(([key])=>asset.id!=='forex'||key!=='volume');

  return <section className="chart-toolbox" aria-label="Toolbox ใต้กราฟ">
    <button className="toolbox-heading" aria-expanded={expanded} onClick={() => setExpanded(value => !value)}><span><i>✧</i> TOOLBOX <small>{asset.symbol} · {hasData ? `${timeframe} ล่าสุด ${latestDay}` : 'รอข้อมูลราคา'}</small></span><b>{expanded ? 'ย่อ −' : 'เปิด +'}</b></button>
    {expanded && <><div className="toolbox-tabs" role="tablist" aria-label="หมวด Toolbox">{[['signals', 'Core Signals'], ['indicators', 'Indicators'], ['alerts', 'Alerts']].map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} className={tab === key ? 'selected' : ''} onClick={() => setTab(key)}>{label}</button>)}</div>
      {tab === 'indicators' && <div className="toolbox-body"><div className="toolbox-section-title"><span><b>◫</b><strong>Technical Indicators</strong><small>คำนวณจาก OHLCV จริง {timeframe} ของ {asset.symbol}</small></span><em className={hasData ? freshness === 'recent' ? 'current' : 'stale' : ''}>{hasData ? !chartOnly && freshness === 'recent' ? 'REAL DATA' : 'HISTORICAL' : 'NO FEED'}</em></div><div className="toolbox-category-tabs"><button className={category === 'trend' ? 'selected' : ''} onClick={() => { setCategory('trend'); setOpenGroup('levels'); }}>↗ Trend</button><button className={category === 'oscillator' ? 'selected' : ''} onClick={() => { setCategory('oscillator'); setOpenGroup('momentum'); }}>∿ Oscillator</button></div>{hasData ? <div className="toolbox-groups">{groups.map(([key, label]) => <div key={key} className="toolbox-group"><button className="toolbox-group-heading" aria-expanded={openGroup === key} onClick={() => setOpenGroup(value => value === key ? '' : key)}>{label}<span>{openGroup === key ? '−' : '+'}</span></button>{openGroup === key && <div className="toolbox-group-content">
            {key === 'levels' && <><Metric label="แนวรับจาก Pivot" note={analysis.levels?.period === 'month' ? 'เดือนก่อนหน้า' : analysis.levels?.period === 'week' ? 'สัปดาห์ก่อนหน้า' : 'วันก่อนหน้า'} value={formatQuotePrice(analysis.support,asset)} tone="positive" /><Metric label="แนวต้านจาก Pivot" note={analysis.levels?.period === 'month' ? 'เดือนก่อนหน้า' : analysis.levels?.period === 'week' ? 'สัปดาห์ก่อนหน้า' : 'วันก่อนหน้า'} value={formatQuotePrice(analysis.resistance,asset)} tone="negative" />{details.pivots ? <><small>Traditional Pivot · {analysis.levels?.referenceFrom}–{analysis.levels?.referenceTo} · H {formatQuotePrice(details.pivots.reference.high,asset)} / L {formatQuotePrice(details.pivots.reference.low,asset)} / C {formatQuotePrice(details.pivots.reference.close,asset)}</small>{[['Traditional', details.pivots.standard]].map(([label, values]) => <div className="toolbox-pivot-set" key={label}><strong>{label}</strong><div className="toolbox-pivot-levels">{['s3','s2','s1','pivot','r1','r2','r3',...(label === 'Camarilla' ? ['s4','r4'] : [])].filter(key => Number.isFinite(values[key])).map(key => <span key={key}>{key.toUpperCase()} <b>{formatQuotePrice(values[key],asset)}</b></span>)}</div></div>)}</> : <div className="toolbox-empty">Pivot ไม่พร้อม · ต้องมีข้อมูล D1 ครบช่วงก่อนหน้าและ High มากกว่า Low</div>}{analysis.levels?.rrPlan && <div className="toolbox-signal-plan"><strong>แผนระยะ 1:2 · ราคาอ้างอิง {formatQuotePrice(analysis.levels.rrPlan.entry,asset)}</strong><div className="toolbox-paired"><span>Stop <b>{formatQuotePrice(analysis.levels.rrPlan.stop,asset)}</b></span><span>เป้า 2R <b>{formatQuotePrice(analysis.levels.rrPlan.target,asset)}</b></span></div><p>{analysis.levels.rrPlan.blocked ? 'WAIT · มีแนวต้านก่อนถึงเป้า 2R ต้องรอทะลุและยืนยันใหม่' : analysis.levels.rrPlan.status === 'UNCONFIRMED_ROOM' ? 'ไม่มี Pivot ต้านเหนือราคาในชุดนี้ ยังไม่ยืนยันพื้นที่ทำกำไร' : 'Pivot ถัดไปมีระยะถึง 2R · ยังต้องยืนยันเงื่อนไขเข้า'}</p><small>{analysis.levels.rrPlan.basis} · เป้า 2R เป็นเป้าคำนวณแผน</small></div>}<div className="toolbox-paired"><span>Donchian Low <b>{formatQuotePrice(details.donchianLower,asset)}</b></span><span>High <b>{formatQuotePrice(details.donchianUpper,asset)}</b></span></div><div className="toolbox-overlay-row"><button className="toolbox-overlay" aria-pressed={indicators.levels} onClick={() => onToggleIndicator('levels')}>{indicators.levels ? '✓' : '+'} แนวรับ / ต้าน</button><button className="toolbox-overlay" aria-pressed={indicators.donchian} onClick={() => onToggleIndicator('donchian')}>{indicators.donchian ? '✓' : '+'} Donchian 20</button></div></>}
            {key === 'averages' && <><Metric label="EMA 20" note="ค่าเฉลี่ยถ่วงน้ำหนัก" value={formatQuotePrice(analysis.ema20,asset)} tone={analysis.price >= analysis.ema20 ? 'positive' : 'negative'} /><Metric label="EMA 50" note="แนวโน้มระยะกลาง" value={formatQuotePrice(analysis.ema50,asset)} /><Metric label="SMA 20" note="ค่าเฉลี่ยธรรมดา" value={formatQuotePrice(details.sma20,asset)} /><div className="toolbox-overlay-row"><button className="toolbox-overlay" aria-pressed={indicators.ema20} onClick={() => onToggleIndicator('ema20')}>{indicators.ema20 ? '✓' : '+'} EMA20</button><button className="toolbox-overlay" aria-pressed={indicators.ema50} onClick={() => onToggleIndicator('ema50')}>{indicators.ema50 ? '✓' : '+'} EMA50</button><button className="toolbox-overlay" aria-pressed={indicators.sma20} onClick={() => onToggleIndicator('sma20')}>{indicators.sma20 ? '✓' : '+'} SMA20</button><button className="toolbox-overlay" aria-pressed={indicators.vwap} disabled={!analysis.vwapSeries?.length} onClick={() => onToggleIndicator('vwap')}>{indicators.vwap ? '✓' : '+'} VWAP*</button></div><small>VWAP* สะสมจากช่วงแท่งที่โหลดเท่านั้น</small></>}
            {key === 'volatility' && <><Metric label="ATR 14" note="ระยะเหวี่ยงเฉลี่ยต่อแท่ง" value={`${formatQuotePrice(details.atr14,asset)} · ${number(details.atrPercent, 1)}%`} /><Metric label="Bollinger Upper" note="20 แท่ง · 2σ" value={formatQuotePrice(analysis.bollinger.upper,asset)} /><Metric label="Bollinger Middle" note="20 แท่ง" value={formatQuotePrice(analysis.bollinger.middle,asset)} /><Metric label="Bollinger Lower" note="20 แท่ง · 2σ" value={formatQuotePrice(analysis.bollinger.lower,asset)} /><button className="toolbox-overlay" aria-pressed={indicators.bollinger} onClick={() => onToggleIndicator('bollinger')}>{indicators.bollinger ? '✓' : '+'} Bollinger Bands บนกราฟ</button></>}
            {key === 'volume' && <><Metric label="Volume ล่าสุด" note={`แท่ง ${timeframe}`} value={number(details.volume, 0)} /><Metric label="เฉลี่ย 20 แท่ง" note="ไม่รวมแท่งล่าสุด" value={number(details.volumeAverage20, 0)} /><Metric label="Relative Volume" note="เทียบค่าเฉลี่ย 20 แท่ง" value={details.relativeVolume === null ? '—' : `${number(details.relativeVolume, 2)}×`} /><Metric label="OBV" note="On Balance Volume" value={number(details.obv, 0)} /><button className="toolbox-overlay" aria-pressed={indicators.volume} onClick={() => onToggleIndicator('volume')}>{indicators.volume ? '✓' : '+'} Volume บนกราฟ</button></>}
            {key === 'momentum' && <><Metric label="RSI 14" note={analysis.rsi14 >= 70 ? 'เขตสูง' : analysis.rsi14 <= 30 ? 'เขตต่ำ' : 'กลางกรอบ'} value={number(analysis.rsi14, 1)} tone={analysis.rsi14 >= 70 ? 'negative' : analysis.rsi14 <= 30 ? 'positive' : ''} /><div className="toolbox-gauge"><i style={{ left: `${Math.max(0, Math.min(100, analysis.rsi14))}%` }} /></div><Metric label="Stochastic %K" note="14 แท่ง" value={number(details.stochasticK, 1)} /><Metric label="Stochastic %D" note="ค่าเฉลี่ย %K สามจุด" value={number(details.stochasticD, 1)} /></>}
            {key === 'macd' && <><Metric label="MACD Line" note="EMA12 − EMA26" value={number(analysis.macd, 3)} /><Metric label="Signal Line" note="EMA9 ของ MACD" value={number(analysis.macdSignal, 3)} /><Metric label="Histogram" note="MACD − Signal" value={number(analysis.macdHistogram, 3)} tone={analysis.macdHistogram >= 0 ? 'positive' : 'negative'} /></>}
          </div>}</div>)}</div> : <div className="toolbox-empty">{bars?.length ? `มีแท่ง ${bars.length} แท่ง · ต้องมีอย่างน้อย 50 แท่งเพื่อเปิดหมวดอินดิเคเตอร์` : 'ยังไม่มีแท่งราคาจริงสำหรับคำนวณ Indicator · ข้อมูล DEMO ไม่ถูกนำมาคิด'}</div>}<p className="toolbox-footnote">{hasData ? `ข้อมูล ${freshness === 'recent' ? 'ตามรอบตลาดล่าสุด' : 'ย้อนหลังเก่า'} · อินดิเคเตอร์ไม่ใช่สัญญาณเข้าเทรด` : 'รอข้อมูลจากผู้ให้บริการราคา'}</p></div>}
      {tab === 'signals' && <div className="toolbox-body"><div className="toolbox-section-title"><span><b>✳</b><strong>Core Signals</strong><small>เงื่อนไขจากกราฟ {asset.symbol} · {timeframe}</small></span><em className={tradePlan?.tradeAllowed ? 'current' : ''}>{tradePlan?.tradeAllowed ? 'WATCH ENTRY' : 'WAIT'}</em></div>{current ? <><div className="toolbox-signal-plan"><strong>{tradePlan?.tradeAllowed ? 'มีโซนราคาที่จับตา' : 'ยังไม่มีแผนที่ผ่านเกณฑ์'}</strong><p>{'ดูสัญญาณระบบเพื่อยืนยันจุดเข้า'}</p>{tradePlan?.tradeAllowed && <div className="toolbox-paired"><span>TP1 <b>{formatQuotePrice(tradePlan.tp1,asset)}</b></span><span>Stop <b>{formatQuotePrice(tradePlan.stopLoss,asset)}</b></span></div>}</div><div className="toolbox-signal-events">{analysis.events.map(event => <span key={event.label} className={event.tone}>{event.label}</span>)}</div></> : <div className="toolbox-empty">รอแท่ง {timeframe} ล่าสุดและประวัติราคาอย่างน้อย 50 แท่ง</div>}<p className="toolbox-footnote">ระดับราคาบนกราฟใช้ประกอบการติดตามสัญญาณ</p></div>}
      {tab === 'alerts' && <div className="toolbox-body"><div className="toolbox-section-title"><span><b>♧</b><strong>AutoPick Alerts</strong><small>เหตุการณ์เข้า · TP1 · SL</small></span><em>WEB</em></div><div className="toolbox-empty">เมื่อ AutoPick เปิดสแกนและมีเหตุการณ์ ระบบจะแจ้งในเว็บขณะเปิดหน้า และบันทึกรายการให้อ่านย้อนหลัง</div><button className="toolbox-alert-action" onClick={onOpenAutomation}>ดู AutoPick และเหตุการณ์ <span>↗</span></button></div>}
    </>}
  </section>;
}
