'use client';
import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, RefreshCw, Users, Wallet } from 'lucide-react';
import MemberAvatar from './member-avatar.jsx';
import { useAdminResource } from './use-admin-resource.mjs';

const NAMES={thai:'หุ้นไทย',dr:'DR',us:'หุ้นสหรัฐฯ'};
const ERRORS={FORBIDDEN:'บัญชีนี้ไม่มีสิทธิจัดการพอร์ตโค้ช',COACH_NOT_FOUND:'ไม่พบพอร์ตที่เปิดให้ดู',COACH_PORTFOLIO_EXISTS:'สมาชิกมีพอร์ตสกุลเงินนี้แล้ว',COACH_INSUFFICIENT_CASH:'เงินจำลองคงเหลือไม่พอ',COACH_CURRENCY_MISMATCH:'ตลาดกับสกุลเงินไม่ตรงกัน',COACH_TRADE_UNAVAILABLE:'ไม้ดังกล่าวปิดไปแล้ว กรุณารีเฟรช',COACH_CONCURRENT_UPDATE:'มีรายการใหม่เข้ามา กรุณารีเฟรชและตรวจเงินคงเหลือก่อนทำรายการใหม่',COACH_INACTIVE:'แอดมินพักพอร์ตนี้ไว้',OPERATION_CONFLICT:'รหัสรายการถูกใช้แล้ว กรุณาตรวจประวัติก่อนทำรายการใหม่',INVALID_COACH_INPUT:'ตรวจชื่อ หุ้น จำนวน ราคา และค่าธรรมเนียมอีกครั้ง',COACH_MEMBER_NOT_FOUND:'ไม่พบสมาชิก LINE นี้',RATE_LIMITED:'ทำรายการถี่เกินไป กรุณารอสักครู่'};
const money=(value,currency)=>new Intl.NumberFormat('th-TH',{style:'currency',currency,maximumFractionDigits:2}).format(value);
const price=value=>value==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:6}).format(value);
const date=value=>value?new Date(value).toLocaleString('th-TH',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Bangkok'}):'—';
function Notice({resource}){return <>{resource.loading&&<p role="status">กำลังโหลดบันทึกพอร์ต…</p>}{resource.error&&<p className="account-alert error" role="alert">{ERRORS[resource.error]||'โหลดข้อมูลไม่ได้ กรุณารีเฟรช'} <button className="account-secondary" onClick={resource.reload}>ลองใหม่</button></p>}</>;}
function Pager({data,onPage,loading}){const pages=Math.max(1,Math.ceil(data.total/7));return <div className="coach-pager"><button className="account-secondary" disabled={loading||data.page<=1} onClick={()=>onPage(data.page-1)}><ArrowLeft size={15}/>ก่อนหน้า</button><span>หน้า {data.page}/{pages} · {data.total} รายการ</span><button className="account-secondary" disabled={loading||data.page>=pages} onClick={()=>onPage(data.page+1)}>ถัดไป<ArrowRight size={15}/></button></div>;}
function PaperLabel(){return <span className="coach-paper-label">พอร์ตจำลองของโค้ช · Paper trade</span>;}
function TradeForm({portfolio,trade,onReview}){
  const close=!!trade;
  return <form className="coach-form" key={trade?.id||portfolio.id} onSubmit={event=>{
    event.preventDefault();const f=new FormData(event.currentTarget);
    onReview({action:close?'close':'open',portfolioId:portfolio.id,tradeId:trade?.id,market:f.get('market'),symbol:f.get('symbol'),quantity:Number(f.get('quantity')),price:Number(f.get('price')),fee:Number(f.get('fee')),note:f.get('note')},close?`ปิดไม้จำลอง ${trade.symbol}`:`เปิดไม้จำลอง ${f.get('symbol')}`);
  }}>
    <h3>{close?`ปิด ${trade.symbol} · ${trade.quantity.toLocaleString()} หุ้น/หน่วย`:'บันทึกการเข้าพอร์ตจำลอง'}</h3>
    <p>ราคาอ้างอิงที่โค้ชหรือผู้ดูแลบันทึก ไม่ใช่ราคาจับคู่จากโบรกเกอร์ เวลาบันทึกมาจากเซิร์ฟเวอร์</p>
    {!close&&<><label>ตลาด<select name="market" defaultValue={portfolio.currency==='USD'?'us':'thai'}>{portfolio.currency==='USD'?<option value="us">หุ้นสหรัฐฯ / ETF</option>:<><option value="thai">หุ้นไทย</option><option value="dr">DR</option></>}</select></label><label>ชื่อหุ้น<input name="symbol" required maxLength={20} placeholder={portfolio.currency==='USD'?'เช่น NVDA':'เช่น CHG หรือ NVDA80'} autoCapitalize="characters"/></label><label>จำนวนหุ้น/หน่วย<input name="quantity" type="number" min="1" max="1000000" step="1" required/></label></>}
    <label>{close?'ราคาออก':'ราคาเข้า'} ({portfolio.currency})<input name="price" type="number" min="0.000001" max="1000000" step="0.000001" required defaultValue={trade?.entryPrice}/></label>
    <label>ค่าธรรมเนียม{close?'ขาออก':'ขาเข้า'} ({portfolio.currency})<input name="fee" type="number" min="0" max="1000000" step="0.01" defaultValue="0" required/></label>
    <label className="coach-form-wide">{close?'เหตุผลปิดไม้':'แผนสั้น ๆ / เหตุผลเข้า'}<input name="note" maxLength={240} required placeholder={close?'เช่น ถึงเป้า / ตัดขาดทุน / ปิดตามแผน':'เช่น ยืนเหนือแนวรับ รอตามแผน'}/></label>
    <button className="account-primary" type="submit">ตรวจรายการก่อนบันทึก</button>
  </form>;
}
function Statistics({portfolio:p,statistics:s}){
  const stats=[['กำไร/ขาดทุนสะสม',money(s.realized,p.currency),`${s.returnPercent.toFixed(2)}% ของทุนเริ่มต้น`,s.realized],['เงินจำลองพร้อมใช้',money(p.cash,p.currency),'หลังหักเงินที่ใช้เปิดไม้'],['ชนะ / แพ้ / เสมอ',`${s.wins} / ${s.losses} / ${s.flat}`,`${s.closed} ไม้ปิด · ${s.open} ไม้ยังถือ`],['Win rate',s.winRate===null?'—':`${s.winRate.toFixed(1)}%`,'นับเฉพาะไม้ปิดทั้งหมด รวมไม้เสมอ'],['มูลค่าตามต้นทุน',money(s.bookBalance,p.currency),'เงินพร้อมใช้ + ต้นทุนไม้ที่ยังถือ'],['ทุนเริ่มต้น',money(p.initialCapital,p.currency),`ค่าธรรมเนียมรวม ${money(s.fees,p.currency)}`]];
  return <div className="coach-stat-grid">{stats.map(([label,value,hint,pnl])=><article key={label}><span>{label}</span><strong className={pnl>0?'coach-profit':pnl<0?'coach-loss':''}>{value}</strong><small>{hint}</small></article>)}</div>;
}
export function CoachPortfolio({id,management=false,admin=false,onBack,onChanged}){
  const [page,setPage]=useState(1),[filter,setFilter]=useState('all'),[closing,setClosing]=useState(null),[entry,setEntry]=useState(false);
  const [draft,setDraft]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const resource=useAdminResource(`/api/coaches/${id}?${new URLSearchParams({management:management?'1':'0',page:String(page),filter})}`);
  const data=resource.data,p=data?.portfolio;
  function review(body,title){setDraft({body:{...body,operationId:crypto.randomUUID()},title});setError('');setMessage('');}
  async function confirm(){if(busy||!draft)return;setBusy(true);setError('');try{
    const response=await fetch('/api/coaches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(draft.body)}),result=await response.json();
    if(!response.ok){setError(ERRORS[result.error]||'บันทึกไม่สำเร็จ กรุณาตรวจรายการและลองใหม่');return;}
    setMessage('บันทึกแล้ว');setDraft(null);setClosing(null);setEntry(false);resource.reload();onChanged?.();
  }catch{setError('ยังไม่ได้รับคำตอบ กดยืนยันรายการเดิมอีกครั้งได้ ระบบป้องกันรายการซ้ำ');}finally{setBusy(false);}}
  return <section className="coach-detail">
    <div className="coach-toolbar">{onBack&&<button className="account-secondary" onClick={onBack}><ArrowLeft size={16}/>พอร์ตโค้ชทั้งหมด</button>}<button className="account-secondary" onClick={resource.reload} disabled={resource.loading||busy}><RefreshCw size={16}/>รีเฟรช</button></div>
    <Notice resource={resource}/>
    {p&&<><header className="coach-identity"><div className="coach-avatar"><MemberAvatar account={{displayName:p.coachName,pictureUrl:p.pictureUrl}} size={56}/></div><div><PaperLabel/><h2>{p.name}</h2><p>โค้ช {p.coachName} · {p.currency} · เริ่ม {date(p.createdAt)}</p></div></header>
      <Statistics portfolio={p} statistics={data.statistics}/>
      <p className="coach-disclosure">ผลจำลองจากราคาเข้า–ออกที่โค้ชหรือผู้ดูแลบันทึก หักค่าธรรมเนียมที่ระบุแล้ว ไม่ใช่พอร์ตเงินจริงหรือผลสแกนย้อนหลัง มูลค่าตามต้นทุนยังไม่รวมกำไร/ขาดทุนของไม้ที่ยังถือ สถิติครอบคลุมตั้งแต่เริ่มพอร์ต</p>
      {management&&<div className="coach-toolbar"><span>{p.active?'พอร์ตพร้อมบันทึก':'พอร์ตพักใช้งาน'} · {p.published?'ลูกค้าดูได้':'ยังไม่เปิดให้ลูกค้าดู'}</span>{data.canManage&&<button className="account-primary" disabled={busy||!!draft} onClick={()=>{setEntry(!entry);setClosing(null);}}>บันทึกเข้าไม้จำลอง</button>}{admin&&<><button className="account-secondary" disabled={busy||!!draft||!p.active} onClick={()=>review({action:'visibility',portfolioId:p.id,published:!p.published,active:p.active},p.published?'ซ่อนพอร์ตจากหน้าลูกค้า':'เปิดให้ลูกค้าดูพอร์ตจำลอง')}>{p.published?'ซ่อนจากลูกค้า':'เปิดให้ลูกค้าดู'}</button><button className="account-secondary" disabled={busy||!!draft} onClick={()=>review({action:'visibility',portfolioId:p.id,active:!p.active,published:false},p.active?'พักพอร์ตและซ่อนจากลูกค้า':'เปิดใช้พอร์ตอีกครั้ง')}>{p.active?'พักพอร์ต':'เปิดใช้พอร์ต'}</button></>}</div>}
      {message&&<p className="account-alert success" role="status"><Check size={16}/>{message}</p>}
      {draft?<div className="coach-confirm" role="region" aria-label="ตรวจรายการ"><PaperLabel/><h3>{draft.title}</h3>{['open','close'].includes(draft.body.action)&&<p>ราคา {price(draft.body.price)} {p.currency} · {draft.body.quantity?`${draft.body.quantity} หุ้น/หน่วย · `:''}ค่าธรรมเนียม {money(draft.body.fee,p.currency)}<br/>เหตุผล: {draft.body.note}</p>}<p>รายการเข้า–ออกที่ยืนยันแล้วแก้ไขหรือลบย้อนหลังไม่ได้</p>{error&&<p role="alert" className="coach-loss">{error}</p>}<div className="coach-toolbar"><button className="account-primary" disabled={busy} onClick={confirm}>{busy?'กำลังบันทึก':'ยืนยันรายการจำลอง'}</button><button className="account-secondary" disabled={busy} onClick={()=>{setDraft(null);setError('');resource.reload();}}>ปิดและตรวจประวัติ</button></div></div>:<>{entry&&data.canManage&&<TradeForm portfolio={p} onReview={review}/>} {closing&&data.canManage&&<><TradeForm portfolio={p} trade={closing} onReview={review}/><button className="account-secondary" onClick={()=>setClosing(null)}>ยกเลิกปิดไม้</button></>}</>}
      <div className="coach-toolbar"><h3>รายการเข้า–ออก</h3><label>แสดง<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1);}}><option value="all">ทุกไม้</option><option value="open">ยังถือ</option><option value="closed">ปิดแล้ว</option></select></label></div>
      <div className="coach-trades">{data.trades.map(t=><article key={t.id}><header><strong>{t.symbol}</strong><span>{NAMES[t.market]} · {t.quantity.toLocaleString()} หุ้น/หน่วย</span><b className={t.pnl>0?'coach-profit':t.pnl<0?'coach-loss':''}>{t.pnl===null?'ยังถือ':t.pnl>0?'ชนะ':t.pnl<0?'แพ้':'เสมอ'}</b></header><div className="coach-trade-prices"><span>เข้า <strong>{price(t.entryPrice)}</strong><small>{date(t.openedAt)}</small></span><span>ออก <strong>{price(t.exitPrice)}</strong><small>{date(t.closedAt)}</small></span><span>กำไร/ขาดทุนสุทธิ <strong className={t.pnl>0?'coach-profit':t.pnl<0?'coach-loss':''}>{t.pnl===null?'—':money(t.pnl,p.currency)}</strong><small>ค่าธรรมเนียม {money(t.entryFee+(t.exitFee||0),p.currency)}</small></span></div><p>แผนเข้า: {t.entryNote}</p>{t.exitNote&&<p>เหตุผลออก: {t.exitNote}</p>}{data.canManage&&!t.closedAt&&<button className="account-secondary" disabled={busy||!!draft} onClick={()=>{setClosing(t);setEntry(false);}}>บันทึกปิดไม้ {t.symbol}</button>}</article>)}</div>
      {!data.trades.length&&<p className="account-empty">ยังไม่มีรายการในหมวดนี้</p>}<Pager data={data} onPage={setPage} loading={resource.loading}/>
    </>}
  </section>;
}
function CreatePortfolio({onCreated}){
  const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[memberPage,setMemberPage]=useState(1),[member,setMember]=useState(null),[pending,setPending]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const members=useAdminResource(`/api/admin/memberships?${new URLSearchParams({q:search,page:String(memberPage),filter:'all'})}`);
  async function create(){if(busy||!pending)return;setBusy(true);setError('');try{const r=await fetch('/api/coaches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(pending)}),result=await r.json();if(!r.ok){setError(ERRORS[result.error]||'สร้างไม่สำเร็จ');return;}setPending(null);onCreated(result.portfolioId);}catch{setError('ยังไม่ได้รับคำตอบ กดยืนยันรายการเดิมซ้ำได้อย่างปลอดภัย');}finally{setBusy(false);}}
  return <section className="coach-create"><h3>แอดมินเพิ่มพอร์ตโค้ช</h3><p>เลือกสมาชิก LINE เพื่อให้สิทธิบันทึกพอร์ตนี้ เริ่มแบบไม่เผยแพร่ หนึ่งสมาชิกมีได้หนึ่งพอร์ตต่อสกุลเงิน</p>
    {!pending&&<><form className="coach-toolbar" onSubmit={e=>{e.preventDefault();setSearch(query.trim());setMemberPage(1);}}><input aria-label="ค้นหาโค้ชจากสมาชิก LINE" value={query} maxLength={80} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาชื่อสมาชิก LINE"/><button className="account-secondary">ค้นหา</button></form><Notice resource={members}/><div className="coach-member-options">{members.data?.members.map(m=><button key={m.id} className={member?.id===m.id?'account-primary':'account-secondary'} onClick={()=>setMember(m)}>{m.display_name}{member?.id===m.id&&<Check size={14}/>}</button>)}</div>{members.data&&<div className="coach-toolbar"><button className="account-secondary" disabled={members.loading||memberPage<=1} onClick={()=>setMemberPage(v=>v-1)}>ก่อนหน้า</button><span>หน้า {members.data.page}</span><button className="account-secondary" disabled={members.loading||memberPage*members.data.pageSize>=members.data.total} onClick={()=>setMemberPage(v=>v+1)}>ถัดไป</button></div>}
      {member&&<form className="coach-form" key={member.id} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setError('');setPending({action:'create',memberId:member.id,name:f.get('name'),currency:f.get('currency'),initialCapital:Number(f.get('capital')),operationId:crypto.randomUUID()});}}><h3>โค้ช {member.display_name}</h3><label>ชื่อพอร์ต<input name="name" maxLength={80} required defaultValue={`พอร์ตโค้ช ${member.display_name}`}/></label><label>สกุลเงิน<select name="currency"><option value="THB">THB · ไทย / DR</option><option value="USD">USD · สหรัฐฯ / ETF</option></select></label><label>ทุนจำลองเริ่มต้น<input name="capital" type="number" step="0.01" min="0.01" max="100000000" defaultValue="100000" required/></label><button className="account-primary">ตรวจรายละเอียด</button></form>}</>}
    {pending&&<div className="coach-confirm"><PaperLabel/><h3>{pending.name}</h3><p>โค้ช {member.display_name} · ทุนจำลอง {money(pending.initialCapital,pending.currency)} · ยังไม่เผยแพร่</p><p>ทุนเริ่มต้นและประวัติจะคงอยู่ ไม่มีการรีเซ็ตผลลัพธ์</p>{error&&<p role="alert" className="coach-loss">{error}</p>}<div className="coach-toolbar"><button className="account-primary" disabled={busy} onClick={create}>{busy?'กำลังสร้าง':'ยืนยันสร้างพอร์ตจำลอง'}</button><button className="account-secondary" disabled={busy} onClick={()=>setPending(null)}>ย้อนกลับ</button></div></div>}
  </section>;
}
export default function CoachHub({mode='public'}){
  const admin=mode==='admin',management=mode!=='public';
  const [page,setPage]=useState(1),[selected,setSelected]=useState(null),[creating,setCreating]=useState(false);
  const resource=useAdminResource(`/api/coaches?${new URLSearchParams({admin:admin?'1':'0',own:mode==='own'?'1':'0',page:String(page)})}`);
  if(selected)return <CoachPortfolio key={selected} id={selected} management={management} admin={admin} onBack={()=>setSelected(null)} onChanged={resource.reload}/>;
  return <section className="coach-hub"><div className="coach-toolbar"><div><h2><Users size={22}/>พอร์ตโค้ช</h2><PaperLabel/></div><button className="account-secondary" onClick={resource.reload} disabled={resource.loading}><RefreshCw size={16}/>รีเฟรช</button>{admin&&<button className="account-primary" onClick={()=>setCreating(!creating)}>{creating?'ปิดแบบฟอร์ม':'เพิ่มโค้ช'}</button>}</div><p>ดูสิ่งที่โค้ชเข้าพอร์ตจำลอง รายการที่ยังถือ และผลกำไร/ขาดทุนจากไม้ที่ปิดแล้ว</p>
    {creating&&<CreatePortfolio onCreated={id=>{setCreating(false);resource.reload();setSelected(id);}}/>}<Notice resource={resource}/>
    <div className="coach-portfolio-grid">{resource.data?.portfolios.map(p=><article key={p.id}><div className="coach-identity"><div className="coach-avatar"><MemberAvatar account={{displayName:p.coachName,pictureUrl:p.pictureUrl}} size={48}/></div><div><PaperLabel/><h3>{p.name}</h3><span>โค้ช {p.coachName} · {p.currency}</span></div></div><p><Wallet size={16}/>เงินจำลองพร้อมใช้ <strong>{money(p.cash,p.currency)}</strong></p>{management&&<p>{p.active?'เปิดใช้งาน':'พักพอร์ต'} · {p.published?'ลูกค้าดูได้':'เฉพาะโค้ชและแอดมิน'}</p>}<button className="account-secondary" onClick={()=>setSelected(p.id)}>ดูไม้เข้า–ออกและสถิติ<ArrowRight size={16}/></button>{p.published&&<a className="coach-public-link" href={`/coaches/${p.id}`}>เปิดหน้าที่ลูกค้าเห็น</a>}</article>)}</div>
    {resource.data&&!resource.data.portfolios.length&&<p className="account-empty">{admin?'ยังไม่มีพอร์ตโค้ช เพิ่มจากสมาชิก LINE ได้เลย':management?'แอดมินยังไม่ได้กำหนดพอร์ตให้บัญชีนี้':'ยังไม่มีพอร์ตโค้ชที่เปิดให้ดู'}</p>}{resource.data&&<Pager data={resource.data} onPage={setPage} loading={resource.loading}/>}
  </section>;
}
