'use client';
import {useState} from 'react';
import {ALL_ASSETS} from '../markets/catalog.mjs';
export default function HoldingsDesk({rights,onSelect,marketId=null}){
 const [market,setMarket]=useState(marketId??'thai'),[symbol,setSymbol]=useState(marketId==='dr'?'AAPL80':marketId==='us'?'NVDA':'PTT'),[cost,setCost]=useState(''),[quantity,setQuantity]=useState('1'),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function refresh(){setBusy(true);setError('');try{const r=await fetch('/api/holdings',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.code);setData(d);}catch{setError('โหลดพอร์ตไม่ได้ ตรวจสิทธิสมาชิกและลองอีกครั้ง');}finally{setBusy(false);}}
 async function save(v){setBusy(true);setError('');try{const r=await fetch('/api/holdings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(v)});if(!r.ok)throw Error();await refresh();}catch{setError('บันทึกไม่ได้ ตรวจสัญลักษณ์ ต้นทุน และจำนวน (สูงสุด 20 รายการ)');}finally{setBusy(false);}}
 if(!rights?.capabilities?.manualDailyScan)return null;
 return <details className="holdings-desk"><summary>หุ้นที่ฉันถือ · แนวโน้มและคะแนนเทคนิค</summary><p>กรอกเอง แยกจากบัญชีโบรกเกอร์ · ประเมินจากราคาปิดรายวันและแผนของคุณ</p><form onSubmit={e=>{e.preventDefault();save({market,symbol:symbol.trim().toUpperCase(),cost,quantity});}}><select hidden={Boolean(marketId)} aria-label="ตลาดหุ้นที่ถือ" value={market} onChange={e=>setMarket(e.target.value)}><option value="thai">หุ้นไทย</option><option value="dr">DR</option><option value="us">หุ้นเมกา</option></select><input aria-label="สัญลักษณ์หุ้น" list="holding-symbols" value={symbol} onChange={e=>setSymbol(e.target.value)} required/><datalist id="holding-symbols">{ALL_ASSETS.filter(a=>a.id===market).map(a=><option key={a.instrumentId??a.symbol} value={a.symbol}/>)}</datalist><input aria-label="ต้นทุนต่อหน่วย" type="number" step="any" min="0.000001" placeholder="ต้นทุนต่อหน่วย" value={cost} onChange={e=>setCost(e.target.value)} required/><input aria-label="จำนวนหุ้น" type="number" step="any" min="0.000001" value={quantity} onChange={e=>setQuantity(e.target.value)} required/><button disabled={busy}>บันทึกหุ้นที่ถือ</button><button type="button" disabled={busy} onClick={refresh}>โหลด / ประเมินใหม่</button></form>{error&&<p role="alert">{error}</p>}{busy&&<p>กำลังอ่านแท่งจริง…</p>}{data&&<><small>{data.basis}</small>{data.results.filter(r=>!marketId||r.market===marketId).map(r=><article key={`${r.market}:${r.symbol}`}><strong>{r.symbol} · {r.score==null?'ไม่มีคะแนน':`${r.score}/100`}</strong><p>ต้นทุน {r.cost} · จำนวน {r.quantity} · ราคาปิด {r.price??'—'} · {r.pnlPercent==null?'ยังคำนวณไม่ได้':`${r.pnlPercent.toFixed(2)}% ก่อนค่าธรรมเนียม`}</p><p>{r.text}</p><b>{r.action}</b><small>{r.latestDay} · {r.source}</small><details><summary>ที่มาคะแนน</summary>{r.factors?.map(f=><p key={f.label}>{f.label} {f.points}/{f.max}</p>)}</details><button onClick={()=>{const a=ALL_ASSETS.find(a=>a.id===r.market&&a.symbol===r.symbol);if(a)onSelect(a);}}>เปิดกราฟ</button><button disabled={busy} onClick={()=>save({...r,action:'remove'})}>นำออกจากรายการ</button></article>)}</>}</details>;
}
